[package]
name = "game_godot_rust_du_an"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

# [[bin]]
# name = "your_binary"
# path = "src/pythonrun.rs"
# windows_subsystem = "windows"

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext.git", rev = "4c7db4833a932c1ff647ac841036f3e631ec2877" }
cpal = "0.18.1"
rustysynth = "1.3"
